const { Sequelize } = require('sequelize');
const ClubRepository = require('../clubRepository');
const ClubModel = require('../clubModel');
const AreaModel = require('../../../../area/repository/sqlite/areaModel');
const ClubEntity = require('../../../entity/club');
const ClubNotFoundError = require('../../error/clubNotFoundError');
const ClubIdNotDefinedError = require('../../error/clubIdNotDefinedError');

const sequelizeInstance = new Sequelize('sqlite::memory');

/**
 * @type ClubRepository
 */
let repository;

const sampleClub = new ClubEntity({
  name: 'Arsenal FC',
  shortName: 'Arsenal',
  tla: 'ARS',
  crestUrl: 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
  address: '75 Drayton Park London N5 1BU',
  phone: '+44 (020) 76195003',
  website: 'http://www.arsenal.com',
  email: 'info@arsenal.co.uk',
  founded: 1886,
  clubColors: 'Red / White',
  venue: 'Emirates Stadium',
  lastUpdated: '2020-05-14T02:41:34Z',
  Area: { id: 1 },
});

beforeAll(() => {
  const club = ClubModel.setup(sequelizeInstance);
  const area = AreaModel.setup(sequelizeInstance);
  club.belongsTo(area);

  repository = new ClubRepository(club, area);
});

beforeEach(async (done) => {
  await sequelizeInstance.sync({ force: true });
  done();
});

test('Crea un equipo cuando la entidad no tiene id', async () => {
  const NEW_AUTOGENERATED_ID = 1;
  const newClub = await repository.save(sampleClub);
  expect(newClub.id).toEqual(NEW_AUTOGENERATED_ID);
});

test('Actualiza un equipo cuando la entidad tiene un id', async () => {
  const NEW_AUTOGENERATED_ID = 1;
  const newClub = await repository.save(sampleClub);
  expect(newClub.id).toEqual(NEW_AUTOGENERATED_ID);

  newClub.name = 'Independiente';
  console.log(newClub);
  const modifiedClub = await repository.save(newClub);
  expect(modifiedClub.id).toEqual(NEW_AUTOGENERATED_ID);
  expect(modifiedClub.name).toEqual('Independiente');
});

test('Borrar un equipo existente devuelve true', async () => {
  const NEW_AUTOGENERATED_ID = 1;
  const newClub = await repository.save(sampleClub);
  expect(newClub.id).toEqual(NEW_AUTOGENERATED_ID);
  await expect(repository.delete(newClub)).resolves.toEqual(true);
  await expect(repository.getById(NEW_AUTOGENERATED_ID)).rejects.toThrow(ClubNotFoundError);
});

test('Borrar un equipo sin parámetros da error', async () => {
  await expect(repository.delete()).rejects.toThrow(ClubIdNotDefinedError);
});

test('Borrar un equipo sin id da error', async () => {
  await expect(repository.delete({})).rejects.toThrow(ClubIdNotDefinedError);
});

test('Borrar un equipo con id inexistente devuelve false', async () => {
  await expect(repository.delete({ id: 1 })).resolves.toEqual(false);
});
